[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
verbosity = 2
ffi = true
odyssey = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
